import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Locale = 'ar' | 'en';
type Direction = 'rtl' | 'ltr';

interface LocalizationContextType {
  locale: Locale;
  direction: Direction;
  t: (key: string) => string;
  changeLocale: (locale: Locale) => void;
}

const defaultContext: LocalizationContextType = {
  locale: 'ar',
  direction: 'rtl',
  t: (key: string) => key,
  changeLocale: () => {},
};

const LocalizationContext = createContext<LocalizationContextType>(defaultContext);

interface LocalizationProviderProps {
  children: ReactNode;
}

export const translations = {
  ar: {
    // Common
    'app.name': 'نظام إدارة المخزون',
    'common.dashboard': 'لوحة التحكم',
    'common.products': 'المنتجات',
    'common.categories': 'التصنيفات',
    'common.product_types': 'أنواع المنتجات',
    'common.inventory': 'المخزون',
    'common.purchases': 'المشتريات',
    'common.transformations': 'التحويلات',
    'common.waste': 'الهدر',
    'common.inventory_audits': 'جرد المخزون',
    'common.reports': 'التقارير',
    'common.users': 'المستخدمين',
    'common.branches': 'الفروع',
    'common.settings': 'الإعدادات',
    'common.logout': 'تسجيل الخروج',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.add': 'إضافة',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.view': 'عرض',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.export': 'تصدير',
    'common.print': 'طباعة',
    'common.date': 'التاريخ',
    'common.status': 'الحالة',
    'common.actions': 'الإجراءات',
    'common.name': 'الاسم',
    'common.description': 'الوصف',
    'common.price': 'السعر',
    'common.cost': 'التكلفة',
    'common.quantity': 'الكمية',
    'common.unit': 'الوحدة',
    'common.total': 'الإجمالي',
    'common.notes': 'ملاحظات',
    'common.created_at': 'تاريخ الإنشاء',
    'common.updated_at': 'تاريخ التحديث',
    'common.created_by': 'بواسطة',
    'common.branch': 'الفرع',
    'common.all_branches': 'جميع الفروع',
    'common.loading': 'جاري التحميل...',
    'common.no_data': 'لا توجد بيانات',
    'common.confirm': 'تأكيد',
    'common.confirm_delete': 'هل أنت متأكد من الحذف؟',
    'common.success': 'تمت العملية بنجاح',
    'common.error': 'حدث خطأ',
    'common.required': 'هذا الحقل مطلوب',
    'common.invalid': 'قيمة غير صالحة',
    'common.from_date': 'من تاريخ',
    'common.to_date': 'إلى تاريخ',
    'common.period': 'الفترة',
    'common.week': 'أسبوع',
    'common.month': 'شهر',
    'common.quarter': 'ربع سنة',
    'common.year': 'سنة',
    'common.last_week': 'آخر أسبوع',
    'common.current_month': 'الشهر الحالي',
    'common.current_quarter': 'الربع الحالي',
    'common.current_year': 'السنة الحالية',
    'common.report_type': 'نوع التقرير',
    'common.summary': 'ملخص',
    'common.detailed': 'تفصيلي',
    'common.sar': 'ريال',
    'common.dark_mode': 'الوضع الداكن',
    'common.light_mode': 'الوضع الفاتح',
    'common.language': 'اللغة',
    'common.arabic': 'العربية',
    'common.english': 'الإنجليزية',

    // Auth
    'auth.login': 'تسجيل الدخول',
    'auth.register': 'إنشاء حساب',
    'auth.forgot_password': 'نسيت كلمة المرور',
    'auth.reset_password': 'إعادة تعيين كلمة المرور',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.confirm_password': 'تأكيد كلمة المرور',
    'auth.full_name': 'الاسم الكامل',
    'auth.phone': 'رقم الهاتف',
    'auth.role': 'الدور',
    'auth.admin': 'مدير',
    'auth.branch_manager': 'مدير فرع',
    'auth.user': 'مستخدم',
    'auth.remember_me': 'تذكرني',
    'auth.login_button': 'تسجيل الدخول',
    'auth.register_button': 'إنشاء حساب',
    'auth.reset_button': 'إعادة تعيين',
    'auth.send_reset_link': 'إرسال رابط إعادة التعيين',
    'auth.no_account': 'ليس لديك حساب؟',
    'auth.have_account': 'لديك حساب بالفعل؟',
    'auth.logout_confirm': 'هل أنت متأكد من تسجيل الخروج؟',

    // Products
    'products.title': 'المنتجات',
    'products.add': 'إضافة منتج',
    'products.edit': 'تعديل منتج',
    'products.view': 'عرض منتج',
    'products.list': 'قائمة المنتجات',
    'products.name': 'اسم المنتج',
    'products.sku': 'رمز المنتج',
    'products.barcode': 'الباركود',
    'products.category': 'التصنيف',
    'products.product_type': 'نوع المنتج',
    'products.unit': 'وحدة القياس',
    'products.min_stock': 'الحد الأدنى للمخزون',
    'products.selling_price': 'سعر البيع',
    'products.is_raw_material': 'مادة خام',
    'products.is_final_product': 'منتج نهائي',
    'products.image': 'صورة المنتج',
    'products.upload_image': 'رفع صورة',
    'products.remove_image': 'إزالة الصورة',
    'products.auto_generate_sku': 'توليد رمز تلقائي',
    'products.scan_barcode': 'مسح الباركود',
    'products.low_stock': 'منتجات منخفضة المخزون',
    'products.out_of_stock': 'منتجات نفذت من المخزون',
    'products.in_stock': 'متوفر في المخزون',
    'products.stock_value': 'قيمة المخزون',
    'products.average_cost': 'متوسط التكلفة',

    // Categories
    'categories.title': 'التصنيفات',
    'categories.add': 'إضافة تصنيف',
    'categories.edit': 'تعديل تصنيف',
    'categories.view': 'عرض تصنيف',
    'categories.list': 'قائمة التصنيفات',
    'categories.name': 'اسم التصنيف',
    'categories.parent': 'التصنيف الأب',
    'categories.no_parent': 'بدون تصنيف أب',

    // Product Types
    'product_types.title': 'أنواع المنتجات',
    'product_types.add': 'إضافة نوع منتج',
    'product_types.edit': 'تعديل نوع منتج',
    'product_types.view': 'عرض نوع منتج',
    'product_types.list': 'قائمة أنواع المنتجات',
    'product_types.name': 'اسم النوع',

    // Inventory
    'inventory.title': 'المخزون',
    'inventory.view': 'عرض المخزون',
    'inventory.adjust': 'تعديل المخزون',
    'inventory.list': 'قائمة المخزون',
    'inventory.product': 'المنتج',
    'inventory.quantity': 'الكمية',
    'inventory.average_cost': 'متوسط التكلفة',
    'inventory.total_value': 'القيمة الإجمالية',
    'inventory.adjustment': 'تعديل المخزون',
    'inventory.adjustment_type': 'نوع التعديل',
    'inventory.increase': 'زيادة',
    'inventory.decrease': 'نقص',
    'inventory.reason': 'سبب التعديل',
    'inventory.current_quantity': 'الكمية الحالية',
    'inventory.new_quantity': 'الكمية الجديدة',
    'inventory.adjustment_quantity': 'كمية التعديل',
    'inventory.adjustment_date': 'تاريخ التعديل',
    'inventory.adjustment_notes': 'ملاحظات التعديل',
    'inventory.adjustment_history': 'سجل تعديلات المخزون',
    'inventory.low_stock_alert': 'تنبيه انخفاض المخزون',
    'inventory.total_inventory_value': 'إجمالي قيمة المخزون',

    // Purchases
    'purchases.title': 'المشتريات',
    'purchases.add': 'إضافة فاتورة شراء',
    'purchases.edit': 'تعديل فاتورة شراء',
    'purchases.view': 'عرض فاتورة شراء',
    'purchases.list': 'قائمة فواتير الشراء',
    'purchases.invoice_number': 'رقم الفاتورة',
    'purchases.invoice_date': 'تاريخ الفاتورة',
    'purchases.supplier': 'المورد',
    'purchases.items': 'العناصر',
    'purchases.add_item': 'إضافة عنصر',
    'purchases.remove_item': 'إزالة العنصر',
    'purchases.product': 'المنتج',
    'purchases.quantity': 'الكمية',
    'purchases.unit_price': 'سعر الوحدة',
    'purchases.total_price': 'السعر الإجمالي',
    'purchases.subtotal': 'المجموع الفرعي',
    'purchases.vat_rate': 'نسبة ضريبة القيمة المضافة',
    'purchases.vat_amount': 'مبلغ ضريبة القيمة المضافة',
    'purchases.total_amount': 'المبلغ الإجمالي',
    'purchases.payment_status': 'حالة الدفع',
    'purchases.paid': 'مدفوع',
    'purchases.unpaid': 'غير مدفوع',
    'purchases.partially_paid': 'مدفوع جزئياً',
    'purchases.payment_method': 'طريقة الدفع',
    'purchases.cash': 'نقداً',
    'purchases.bank_transfer': 'تحويل بنكي',
    'purchases.credit_card': 'بطاقة ائتمان',
    'purchases.payment_reference': 'مرجع الدفع',
    'purchases.payment_notes': 'ملاحظات الدفع',
    'purchases.payment_date': 'تاريخ الدفع',
    'purchases.payment_amount': 'مبلغ الدفع',
    'purchases.remaining_amount': 'المبلغ المتبقي',
    'purchases.add_payment': 'إضافة دفعة',
    'purchases.payment_history': 'سجل الدفعات',
    'purchases.total_purchases': 'إجمالي المشتريات',
    'purchases.total_vat': 'إجمالي ضريبة القيمة المضافة',
    'purchases.invoice_count': 'عدد الفواتير',
    'purchases.supplier_count': 'عدد الموردين',
    'purchases.product_count': 'عدد المنتجات',
    'purchases.by_supplier': 'المشتريات حسب المورد',
    'purchases.by_product': 'المشتريات حسب المنتج',
    'purchases.trend': 'اتجاه المشتريات',
    'purchases.invoice_details': 'تفاصيل الفاتورة',

    // Transformations
    'transformations.title': 'التحويلات',
    'transformations.add': 'إضافة عملية تحويل',
    'transformations.edit': 'تعديل عملية تحويل',
    'transformations.view': 'عرض عملية تحويل',
    'transformations.list': 'قائمة عمليات التحويل',
    'transformations.reference_number': 'رقم المرجع',
    'transformations.date': 'تاريخ التحويل',
    'transformations.output_product': 'المنتج الناتج',
    'transformations.output_quantity': 'كمية الناتج',
    'transformations.input_materials': 'المواد الخام',
    'transformations.add_material': 'إضافة مادة خام',
    'transformations.remove_material': 'إزالة مادة خام',
    'transformations.material': 'المادة الخام',
    'transformations.material_quantity': 'كمية المادة',
    'transformations.material_cost': 'تكلفة المادة',
    'transformations.total_materials_cost': 'إجمالي تكلفة المواد',
    'transformations.output_cost': 'تكلفة المنتج الناتج',
    'transformations.status': 'الحالة',
    'transformations.draft': 'مسودة',
    'transformations.completed': 'مكتمل',
    'transformations.cancelled': 'ملغي',
    'transformations.complete': 'إكمال التحويل',
    'transformations.cancel': 'إلغاء التحويل',
    'transformations.confirm_complete': 'هل أنت متأكد من إكمال عملية التحويل؟ سيتم تحديث المخزون.',
    'transformations.confirm_cancel': 'هل أنت متأكد من إلغاء عملية التحويل؟',
    'transformations.count': 'عدد عمليات التحويل',

    // Waste
    'waste.title': 'الهدر',
    'waste.add': 'إضافة هدر',
    'waste.edit': 'تعديل هدر',
    'waste.view': 'عرض هدر',
    'waste.list': 'قائمة الهدر',
    'waste.date': 'تاريخ الهدر',
    'waste.product': 'المنتج',
    'waste.quantity': 'الكمية',
    'waste.cost': 'التكلفة',
    'waste.reason': 'سبب الهدر',
    'waste.notes': 'ملاحظات',
    'waste.expired': 'منتهي الصلاحية',
    'waste.damaged': 'تالف',
    'waste.lost': 'مفقود',
    'waste.other': 'أخرى',
    'waste.total_cost': 'إجمالي تكلفة الهدر',
    'waste.record_count': 'عدد سجلات الهدر',
    'waste.product_count': 'عدد المنتجات المهدرة',
    'waste.daily_average': 'متوسط الهدر اليومي',
    'waste.by_product': 'الهدر حسب المنتج',
    'waste.by_reason': 'الهدر حسب السبب',
    'waste.trend': 'اتجاه الهدر',
    'waste.details': 'تفاصيل الهدر',

    // Inventory Audits
    'inventory_audits.title': 'جرد المخزون',
    'inventory_audits.add': 'إضافة جرد',
    'inventory_audits.edit': 'تعديل جرد',
    'inventory_audits.view': 'عرض جرد',
    'inventory_audits.list': 'قائمة الجرد',
    'inventory_audits.reference_number': 'رقم المرجع',
    'inventory_audits.audit_date': 'تاريخ الجرد',
    'inventory_audits.branch': 'الفرع',
    'inventory_audits.status': 'الحالة',
    'inventory_audits.draft': 'مسودة',
    'inventory_audits.in_progress': 'قيد التنفيذ',
    'inventory_audits.completed': 'مكتمل',
    'inventory_audits.cancelled': 'ملغي',
    'inventory_audits.notes': 'ملاحظات',
    'inventory_audits.items': 'العناصر',
    'inventory_audits.product': 'المنتج',
    'inventory_audits.expected_quantity': 'الكمية المتوقعة',
    'inventory_audits.actual_quantity': 'الكمية الفعلية',
    'inventory_audits.difference': 'الفرق',
    'inventory_audits.item_notes': 'ملاحظات العنصر',
    'inventory_audits.complete': 'إكمال الجرد',
    'inventory_audits.cancel': 'إلغاء الجرد',
    'inventory_audits.save': 'حفظ والعودة لاحقاً',
    'inventory_audits.confirm_complete': 'هل أنت متأكد من إكمال الجرد؟ سيتم تحديث المخزون بناءً على الكميات الفعلية.',
    'inventory_audits.confirm_cancel': 'هل أنت متأكد من إلغاء الجرد؟',
    'inventory_audits.item_count': 'عدد العناصر',
    'inventory_audits.completed_at': 'تاريخ الإكمال',
    'inventory_audits.completed_by': 'تم الإكمال بواسطة',
    'inventory_audits.summary': 'ملخص نتائج الجرد',
    'inventory_audits.total_items': 'إجمالي العناصر',
    'inventory_audits.items_with_difference': 'عناصر بها فروقات',
    'inventory_audits.positive_items': 'عناصر بزيادة',
    'inventory_audits.negative_items': 'عناصر بنقص',
    'inventory_audits.no_change_items': 'عناصر بدون تغيير',
    'inventory_audits.net_difference': 'صافي الفرق',
    'inventory_audits.total_positive': 'إجمالي الزيادة',
    'inventory_audits.total_negative': 'إجمالي النقص',
    'inventory_audits.important_note': 'ملاحظة هامة',
    'inventory_audits.note_content': 'بعد إنشاء الجرد، ستتمكن من إدخال الكميات الفعلية للمنتجات في المخزون. سيقوم النظام بمقارنة الكميات الفعلية مع الكميات المتوقعة وتسجيل الفروقات.',

    // Reports
    'reports.title': 'التقارير',
    'reports.purchases': 'تقرير المشتريات',
    'reports.waste': 'تقرير الهدر',
    'reports.transformations': 'تقرير التحويلات',
    'reports.inventory': 'تقرير المخزون',
    'reports.inventory_audits': 'تقرير جرد المخزون',
    'reports.period': 'الفترة',
    'reports.branch': 'الفرع',
    'reports.export_csv': 'تصدير CSV',
    'reports.print': 'طباعة',
    'reports.filter': 'تصفية',
    'reports.from_date': 'من تاريخ',
    'reports.to_date': 'إلى تاريخ',
    'reports.report_type': 'نوع التقرير',
    'reports.summary': 'ملخص',
    'reports.detailed': 'تفصيلي',

    // Dashboard
    'dashboard.title': 'لوحة التحكم',
    'dashboard.total_products': 'إجمالي المنتجات',
    'dashboard.inventory_value': 'قيمة المخزون',
    'dashboard.low_stock_items': 'منتجات منخفضة المخزون',
    'dashboard.purchases_value': 'قيمة المشتريات',
    'dashboard.waste_value': 'قيمة الهدر',
    'dashboard.transformations_count': 'عمليات التصنيع',
    'dashboard.inventory_by_category': 'قيمة المخزون حسب التصنيف',
    'dashboard.inventory_by_product_type': 'قيمة المخزون حسب نوع المنتج',
    'dashboard.purchases_trend': 'اتجاه المشتريات',
    'dashboard.waste_trend': 'اتجاه الهدر',
    'dashboard.quick_links': 'روابط سريعة',
    'dashboard.view_inventory': 'عرض المخزون',
    'dashboard.create_purchase': 'فاتورة شراء',
    'dashboard.create_transformation': 'عملية تصنيع',
    'dashboard.create_audit': 'جرد المخزون',

    // Users
    'users.title': 'المستخدمين',
    'users.add': 'إضافة مستخدم',
    'users.edit': 'تعديل مستخدم',
    'users.view': 'عرض مستخدم',
    'users.list': 'قائمة المستخدمين',
    'users.full_name': 'الاسم الكامل',
    'users.email': 'البريد الإلكتروني',
    'users.phone': 'رقم الهاتف',
    'users.role': 'الدور',
    'users.branch': 'الفرع',
    'users.status': 'الحالة',
    'users.active': 'نشط',
    'users.inactive': 'غير نشط',
    'users.password': 'كلمة المرور',
    'users.confirm_password': 'تأكيد كلمة المرور',
    'users.change_password': 'تغيير كلمة المرور',
    'users.last_login': 'آخر تسجيل دخول',

    // Branches
    'branches.title': 'الفروع',
    'branches.add': 'إضافة فرع',
    'branches.edit': 'تعديل فرع',
    'branches.view': 'عرض فرع',
    'branches.list': 'قائمة الفروع',
    'branches.name': 'اسم الفرع',
    'branches.address': 'العنوان',
    'branches.city': 'المدينة',
    'branches.phone': 'رقم الهاتف',
    'branches.manager': 'المدير',
    'branches.status': 'الحالة',
    'branches.active': 'نشط',
    'branches.inactive': 'غير نشط',

    // Settings
    'settings.title': 'الإعدادات',
    'settings.general': 'الإعدادات العامة',
    'settings.company': 'معلومات الشركة',
    'settings.company_name': 'اسم الشركة',
    'settings.company_logo': 'شعار الشركة',
    'settings.company_address': 'عنوان الشركة',
    'settings.company_phone': 'رقم هاتف الشركة',
    'settings.company_email': 'بريد الشركة الإلكتروني',
    'settings.company_website': 'موقع الشركة الإلكتروني',
    'settings.company_vat_number': 'الرقم الضريبي',
    'settings.company_cr_number': 'رقم السجل التجاري',
    'settings.appearance': 'المظهر',
    'settings.language': 'اللغة',
    'settings.theme': 'السمة',
    'settings.dark_mode': 'الوضع الداكن',
    'settings.light_mode': 'الوضع الفاتح',
    'settings.notifications': 'الإشعارات',
    'settings.low_stock_notifications': 'إشعارات انخفاض المخزون',
    'settings.expiry_notifications': 'إشعارات انتهاء الصلاحية',
    'settings.save_settings': 'حفظ الإعدادات',
  },
  en: {
    // Common
    'app.name': 'Inventory Management System',
    'common.dashboard': 'Dashboard',
    'common.products': 'Products',
    'common.categories': 'Categories',
    'common.product_types': 'Product Types',
    'common.inventory': 'Inventory',
    'common.purchases': 'Purchases',
    'common.transformations': 'Transformations',
    'common.waste': 'Waste',
    'common.inventory_audits': 'Inventory Audits',
    'common.reports': 'Reports',
    'common.users': 'Users',
    'common.branches': 'Branches',
    'common.settings': 'Settings',
    'common.logout': 'Logout',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.add': 'Add',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.print': 'Print',
    'common.date': 'Date',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.name': 'Name',
    'common.description': 'Description',
    'common.price': 'Price',
    'common.cost': 'Cost',
    'common.quantity': 'Quantity',
    'common.unit': 'Unit',
    'common.total': 'Total',
    'common.notes': 'Notes',
    'common.created_at': 'Created At',
    'common.updated_at': 'Updated At',
    'common.created_by': 'Created By',
    'common.branch': 'Branch',
    'common.all_branches': 'All Branches',
    'common.loading': 'Loading...',
    'common.no_data': 'No data available',
    'common.confirm': 'Confirm',
    'common.confirm_delete': 'Are you sure you want to delete?',
    'common.success': 'Operation completed successfully',
    'common.error': 'An error occurred',
    'common.required': 'This field is required',
    'common.invalid': 'Invalid value',
    'common.from_date': 'From Date',
    'common.to_date': 'To Date',
    'common.period': 'Period',
    'common.week': 'Week',
    'common.month': 'Month',
    'common.quarter': 'Quarter',
    'common.year': 'Year',
    'common.last_week': 'Last Week',
    'common.current_month': 'Current Month',
    'common.current_quarter': 'Current Quarter',
    'common.current_year': 'Current Year',
    'common.report_type': 'Report Type',
    'common.summary': 'Summary',
    'common.detailed': 'Detailed',
    'common.sar': 'SAR',
    'common.dark_mode': 'Dark Mode',
    'common.light_mode': 'Light Mode',
    'common.language': 'Language',
    'common.arabic': 'Arabic',
    'common.english': 'English',

    // Auth
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.forgot_password': 'Forgot Password',
    'auth.reset_password': 'Reset Password',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirm_password': 'Confirm Password',
    'auth.full_name': 'Full Name',
    'auth.phone': 'Phone Number',
    'auth.role': 'Role',
    'auth.admin': 'Admin',
    'auth.branch_manager': 'Branch Manager',
    'auth.user': 'User',
    'auth.remember_me': 'Remember Me',
    'auth.login_button': 'Login',
    'auth.register_button': 'Register',
    'auth.reset_button': 'Reset',
    'auth.send_reset_link': 'Send Reset Link',
    'auth.no_account': 'Don\'t have an account?',
    'auth.have_account': 'Already have an account?',
    'auth.logout_confirm': 'Are you sure you want to logout?',

    // Products
    'products.title': 'Products',
    'products.add': 'Add Product',
    'products.edit': 'Edit Product',
    'products.view': 'View Product',
    'products.list': 'Product List',
    'products.name': 'Product Name',
    'products.sku': 'SKU',
    'products.barcode': 'Barcode',
    'products.category': 'Category',
    'products.product_type': 'Product Type',
    'products.unit': 'Unit',
    'products.min_stock': 'Minimum Stock',
    'products.selling_price': 'Selling Price',
    'products.is_raw_material': 'Raw Material',
    'products.is_final_product': 'Final Product',
    'products.image': 'Product Image',
    'products.upload_image': 'Upload Image',
    'products.remove_image': 'Remove Image',
    'products.auto_generate_sku': 'Auto Generate SKU',
    'products.scan_barcode': 'Scan Barcode',
    'products.low_stock': 'Low Stock Products',
    'products.out_of_stock': 'Out of Stock Products',
    'products.in_stock': 'In Stock',
    'products.stock_value': 'Stock Value',
    'products.average_cost': 'Average Cost',

    // Categories
    'categories.title': 'Categories',
    'categories.add': 'Add Category',
    'categories.edit': 'Edit Category',
    'categories.view': 'View Category',
    'categories.list': 'Category List',
    'categories.name': 'Category Name',
    'categories.parent': 'Parent Category',
    'categories.no_parent': 'No Parent Category',

    // Product Types
    'product_types.title': 'Product Types',
    'product_types.add': 'Add Product Type',
    'product_types.edit': 'Edit Product Type',
    'product_types.view': 'View Product Type',
    'product_types.list': 'Product Type List',
    'product_types.name': 'Type Name',

    // Inventory
    'inventory.title': 'Inventory',
    'inventory.view': 'View Inventory',
    'inventory.adjust': 'Adjust Inventory',
    'inventory.list': 'Inventory List',
    'inventory.product': 'Product',
    'inventory.quantity': 'Quantity',
    'inventory.average_cost': 'Average Cost',
    'inventory.total_value': 'Total Value',
    'inventory.adjustment': 'Inventory Adjustment',
    'inventory.adjustment_type': 'Adjustment Type',
    'inventory.increase': 'Increase',
    'inventory.decrease': 'Decrease',
    'inventory.reason': 'Reason',
    'inventory.current_quantity': 'Current Quantity',
    'inventory.new_quantity': 'New Quantity',
    'inventory.adjustment_quantity': 'Adjustment Quantity',
    'inventory.adjustment_date': 'Adjustment Date',
    'inventory.adjustment_notes': 'Adjustment Notes',
    'inventory.adjustment_history': 'Adjustment History',
    'inventory.low_stock_alert': 'Low Stock Alert',
    'inventory.total_inventory_value': 'Total Inventory Value',

    // Purchases
    'purchases.title': 'Purchases',
    'purchases.add': 'Add Purchase Invoice',
    'purchases.edit': 'Edit Purchase Invoice',
    'purchases.view': 'View Purchase Invoice',
    'purchases.list': 'Purchase Invoice List',
    'purchases.invoice_number': 'Invoice Number',
    'purchases.invoice_date': 'Invoice Date',
    'purchases.supplier': 'Supplier',
    'purchases.items': 'Items',
    'purchases.add_item': 'Add Item',
    'purchases.remove_item': 'Remove Item',
    'purchases.product': 'Product',
    'purchases.quantity': 'Quantity',
    'purchases.unit_price': 'Unit Price',
    'purchases.total_price': 'Total Price',
    'purchases.subtotal': 'Subtotal',
    'purchases.vat_rate': 'VAT Rate',
    'purchases.vat_amount': 'VAT Amount',
    'purchases.total_amount': 'Total Amount',
    'purchases.payment_status': 'Payment Status',
    'purchases.paid': 'Paid',
    'purchases.unpaid': 'Unpaid',
    'purchases.partially_paid': 'Partially Paid',
    'purchases.payment_method': 'Payment Method',
    'purchases.cash': 'Cash',
    'purchases.bank_transfer': 'Bank Transfer',
    'purchases.credit_card': 'Credit Card',
    'purchases.payment_reference': 'Payment Reference',
    'purchases.payment_notes': 'Payment Notes',
    'purchases.payment_date': 'Payment Date',
    'purchases.payment_amount': 'Payment Amount',
    'purchases.remaining_amount': 'Remaining Amount',
    'purchases.add_payment': 'Add Payment',
    'purchases.payment_history': 'Payment History',
    'purchases.total_purchases': 'Total Purchases',
    'purchases.total_vat': 'Total VAT',
    'purchases.invoice_count': 'Invoice Count',
    'purchases.supplier_count': 'Supplier Count',
    'purchases.product_count': 'Product Count',
    'purchases.by_supplier': 'Purchases by Supplier',
    'purchases.by_product': 'Purchases by Product',
    'purchases.trend': 'Purchase Trend',
    'purchases.invoice_details': 'Invoice Details',

    // Transformations
    'transformations.title': 'Transformations',
    'transformations.add': 'Add Transformation',
    'transformations.edit': 'Edit Transformation',
    'transformations.view': 'View Transformation',
    'transformations.list': 'Transformation List',
    'transformations.reference_number': 'Reference Number',
    'transformations.date': 'Transformation Date',
    'transformations.output_product': 'Output Product',
    'transformations.output_quantity': 'Output Quantity',
    'transformations.input_materials': 'Input Materials',
    'transformations.add_material': 'Add Material',
    'transformations.remove_material': 'Remove Material',
    'transformations.material': 'Material',
    'transformations.material_quantity': 'Material Quantity',
    'transformations.material_cost': 'Material Cost',
    'transformations.total_materials_cost': 'Total Materials Cost',
    'transformations.output_cost': 'Output Cost',
    'transformations.status': 'Status',
    'transformations.draft': 'Draft',
    'transformations.completed': 'Completed',
    'transformations.cancelled': 'Cancelled',
    'transformations.complete': 'Complete Transformation',
    'transformations.cancel': 'Cancel Transformation',
    'transformations.confirm_complete': 'Are you sure you want to complete this transformation? Inventory will be updated.',
    'transformations.confirm_cancel': 'Are you sure you want to cancel this transformation?',
    'transformations.count': 'Transformation Count',

    // Waste
    'waste.title': 'Waste',
    'waste.add': 'Add Waste',
    'waste.edit': 'Edit Waste',
    'waste.view': 'View Waste',
    'waste.list': 'Waste List',
    'waste.date': 'Waste Date',
    'waste.product': 'Product',
    'waste.quantity': 'Quantity',
    'waste.cost': 'Cost',
    'waste.reason': 'Reason',
    'waste.notes': 'Notes',
    'waste.expired': 'Expired',
    'waste.damaged': 'Damaged',
    'waste.lost': 'Lost',
    'waste.other': 'Other',
    'waste.total_cost': 'Total Waste Cost',
    'waste.record_count': 'Waste Record Count',
    'waste.product_count': 'Wasted Product Count',
    'waste.daily_average': 'Daily Waste Average',
    'waste.by_product': 'Waste by Product',
    'waste.by_reason': 'Waste by Reason',
    'waste.trend': 'Waste Trend',
    'waste.details': 'Waste Details',

    // Inventory Audits
    'inventory_audits.title': 'Inventory Audits',
    'inventory_audits.add': 'Add Audit',
    'inventory_audits.edit': 'Edit Audit',
    'inventory_audits.view': 'View Audit',
    'inventory_audits.list': 'Audit List',
    'inventory_audits.reference_number': 'Reference Number',
    'inventory_audits.audit_date': 'Audit Date',
    'inventory_audits.branch': 'Branch',
    'inventory_audits.status': 'Status',
    'inventory_audits.draft': 'Draft',
    'inventory_audits.in_progress': 'In Progress',
    'inventory_audits.completed': 'Completed',
    'inventory_audits.cancelled': 'Cancelled',
    'inventory_audits.notes': 'Notes',
    'inventory_audits.items': 'Items',
    'inventory_audits.product': 'Product',
    'inventory_audits.expected_quantity': 'Expected Quantity',
    'inventory_audits.actual_quantity': 'Actual Quantity',
    'inventory_audits.difference': 'Difference',
    'inventory_audits.item_notes': 'Item Notes',
    'inventory_audits.complete': 'Complete Audit',
    'inventory_audits.cancel': 'Cancel Audit',
    'inventory_audits.save': 'Save and Return Later',
    'inventory_audits.confirm_complete': 'Are you sure you want to complete this audit? Inventory will be updated based on actual quantities.',
    'inventory_audits.confirm_cancel': 'Are you sure you want to cancel this audit?',
    'inventory_audits.item_count': 'Item Count',
    'inventory_audits.completed_at': 'Completed At',
    'inventory_audits.completed_by': 'Completed By',
    'inventory_audits.summary': 'Audit Results Summary',
    'inventory_audits.total_items': 'Total Items',
    'inventory_audits.items_with_difference': 'Items with Difference',
    'inventory_audits.positive_items': 'Items with Surplus',
    'inventory_audits.negative_items': 'Items with Shortage',
    'inventory_audits.no_change_items': 'Items with No Change',
    'inventory_audits.net_difference': 'Net Difference',
    'inventory_audits.total_positive': 'Total Surplus',
    'inventory_audits.total_negative': 'Total Shortage',
    'inventory_audits.important_note': 'Important Note',
    'inventory_audits.note_content': 'After creating the audit, you will be able to enter the actual quantities of products in inventory. The system will compare actual quantities with expected quantities and record the differences.',

    // Reports
    'reports.title': 'Reports',
    'reports.purchases': 'Purchases Report',
    'reports.waste': 'Waste Report',
    'reports.transformations': 'Transformations Report',
    'reports.inventory': 'Inventory Report',
    'reports.inventory_audits': 'Inventory Audits Report',
    'reports.period': 'Period',
    'reports.branch': 'Branch',
    'reports.export_csv': 'Export CSV',
    'reports.print': 'Print',
    'reports.filter': 'Filter',
    'reports.from_date': 'From Date',
    'reports.to_date': 'To Date',
    'reports.report_type': 'Report Type',
    'reports.summary': 'Summary',
    'reports.detailed': 'Detailed',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.total_products': 'Total Products',
    'dashboard.inventory_value': 'Inventory Value',
    'dashboard.low_stock_items': 'Low Stock Items',
    'dashboard.purchases_value': 'Purchases Value',
    'dashboard.waste_value': 'Waste Value',
    'dashboard.transformations_count': 'Manufacturing Operations',
    'dashboard.inventory_by_category': 'Inventory Value by Category',
    'dashboard.inventory_by_product_type': 'Inventory Value by Product Type',
    'dashboard.purchases_trend': 'Purchases Trend',
    'dashboard.waste_trend': 'Waste Trend',
    'dashboard.quick_links': 'Quick Links',
    'dashboard.view_inventory': 'View Inventory',
    'dashboard.create_purchase': 'Purchase Invoice',
    'dashboard.create_transformation': 'Manufacturing Operation',
    'dashboard.create_audit': 'Inventory Audit',

    // Users
    'users.title': 'Users',
    'users.add': 'Add User',
    'users.edit': 'Edit User',
    'users.view': 'View User',
    'users.list': 'User List',
    'users.full_name': 'Full Name',
    'users.email': 'Email',
    'users.phone': 'Phone',
    'users.role': 'Role',
    'users.branch': 'Branch',
    'users.status': 'Status',
    'users.active': 'Active',
    'users.inactive': 'Inactive',
    'users.password': 'Password',
    'users.confirm_password': 'Confirm Password',
    'users.change_password': 'Change Password',
    'users.last_login': 'Last Login',

    // Branches
    'branches.title': 'Branches',
    'branches.add': 'Add Branch',
    'branches.edit': 'Edit Branch',
    'branches.view': 'View Branch',
    'branches.list': 'Branch List',
    'branches.name': 'Branch Name',
    'branches.address': 'Address',
    'branches.city': 'City',
    'branches.phone': 'Phone',
    'branches.manager': 'Manager',
    'branches.status': 'Status',
    'branches.active': 'Active',
    'branches.inactive': 'Inactive',

    // Settings
    'settings.title': 'Settings',
    'settings.general': 'General Settings',
    'settings.company': 'Company Information',
    'settings.company_name': 'Company Name',
    'settings.company_logo': 'Company Logo',
    'settings.company_address': 'Company Address',
    'settings.company_phone': 'Company Phone',
    'settings.company_email': 'Company Email',
    'settings.company_website': 'Company Website',
    'settings.company_vat_number': 'VAT Number',
    'settings.company_cr_number': 'CR Number',
    'settings.appearance': 'Appearance',
    'settings.language': 'Language',
    'settings.theme': 'Theme',
    'settings.dark_mode': 'Dark Mode',
    'settings.light_mode': 'Light Mode',
    'settings.notifications': 'Notifications',
    'settings.low_stock_notifications': 'Low Stock Notifications',
    'settings.expiry_notifications': 'Expiry Notifications',
    'settings.save_settings': 'Save Settings',
  },
};

export const LocalizationProvider = ({ children }: LocalizationProviderProps) => {
  const [locale, setLocale] = useState<Locale>('ar');
  const [direction, setDirection] = useState<Direction>('rtl');

  useEffect(() => {
    // Set direction based on locale
    setDirection(locale === 'ar' ? 'rtl' : 'ltr');
    
    // Set HTML dir attribute
    document.documentElement.dir = locale === 'ar' ? 'rtl' : 'ltr';
    
    // Set HTML lang attribute
    document.documentElement.lang = locale;
    
    // Add appropriate class to body for RTL/LTR styling
    if (locale === 'ar') {
      document.body.classList.add('rtl');
      document.body.classList.remove('ltr');
    } else {
      document.body.classList.add('ltr');
      document.body.classList.remove('rtl');
    }
  }, [locale]);

  const t = (key: string): string => {
    return translations[locale][key] || key;
  };

  const changeLocale = (newLocale: Locale) => {
    setLocale(newLocale);
  };

  return (
    <LocalizationContext.Provider value={{ locale, direction, t, changeLocale }}>
      {children}
    </LocalizationContext.Provider>
  );
};

export const useLocalization = () => useContext(LocalizationContext);
